Add encrypted Caddy configuration and utilities
- Encrypt and organize multiple Caddy configuration files using Ansible Vault.
- Introduce `caddy-fmt-encrypt.fish` script for formatting and encrypting Caddy configuration files.
- Add `caddy-setup-certs.fish` script for handling Let's Encrypt TLS certificates and notifying via `ntfy`.
- Update project run configuration for the `caddy-fmt-encrypt.fish` utility.

diff --git a/playbooks/lets-encrypt.yaml b/playbooks/lets-encrypt.yaml
--- a/playbooks/lets-encrypt.yaml
+++ b/playbooks/lets-encrypt.yaml
@@ -11,106 +11,76 @@
       
     - name: Lets Encrypt | Renew
       ansible.builtin.shell: |
-        set -euo pipefail
+        set -l lego_version "latest"
+        set -l email "{{ lets_encrypt_email }}"
+        set -l cf_dns_api_token "{{ cf_dns_api_token }}"
+        set -l cf_polling_interval "10"
+        set -l cf_propagation_timeout "180"
+        set -l cf_ttl "120"
+        set -l domains "{{ lets_encrypt_domains }}"
+        set -l lets_encrypt_path "{{ lets_encrypt_path }}"
+        set -l dns_servers "1.1.1.1:53,1.0.0.1:53"
+        set -l lego_domain_flags ""
         
-        export lego_version="latest"
-        export email="{{ lets_encrypt_email }}"
-        export cf_dns_api_token="{{ cf_dns_api_token }}"
-        export cf_polling_interval="30"
-        export cf_propagation_timeout="130"
-        export cf_ttl="120"
-        export domains="{{ lets_encrypt_domains }}"
-        export lets_encrypt_path="{{ lets_encrypt_path }}"
-        export dns_servers="1.1.1.1:53,1.0.0.1:53"
+        for domain in (string split " " $domains)
+            set --append lego_domain_flags --domains=\""$domain"\" --domains=\""*.$domain"\"
+        end
         
-        function renew() {
-          read -ra domain_array <<< "$domains"
+        set -l command_to_run podman run --rm \
+          --name=letsencrypt \
+          --volume="$lets_encrypt_path/.lego:/.lego:z" \
+          --env=CF_DNS_API_TOKEN="$cf_dns_api_token" \
+          --env=CLOUDFLARE_POLLING_INTERVAL="$cf_polling_interval" \
+          --env=CLOUDFLARE_PROPAGATION_TIMEOUT="$cf_propagation_timeout" \
+          --env=CLOUDFLARE_TTL="$cf_ttl" \
+          docker.io/goacme/lego:"$lego_version" \
+            --accept-tos \
+            --email="$email" \
+            --dns.resolvers="$dns_servers" \
+            --dns="cloudflare" \
+            $lego_domain_flags \
+            renew --no-random-sleep
         
-          for domain in "${domain_array[@]}"; do
-            echo "------ $domain -------" >&2
-            podman run --rm \
-              --name=letsencrypt \
-              --volume="$lets_encrypt_path/.lego:/.lego:z" \
-              --env=CF_DNS_API_TOKEN="$cf_dns_api_token" \
-              --env=CLOUDFLARE_POLLING_INTERVAL="$cf_polling_interval" \
-              --env=CLOUDFLARE_PROPAGATION_TIMEOUT="$cf_propagation_timeout" \
-              --env=CLOUDFLARE_TTL="$cf_ttl" \
-              docker.io/goacme/lego:"$lego_version" \
-                --accept-tos \
-                --dns.resolvers="$dns_servers" \
-                --email="$email" \
-                --dns=cloudflare \
-                --domains="$domain" \
-                --domains="*.$domain" \
-                renew --no-random-sleep
-          done
-        }
-        
-        renew
+        eval $command_to_run
       args:
-        executable: /usr/bin/bash
+        executable: /usr/bin/fish
       register: lets_encrypt_renew_output
       changed_when: "'Server responded with a certificate.' in lets_encrypt_renew_output.stderr"
     
     - name: Lets Encrypt | Caddy setup certs
       ansible.builtin.shell: |
-        export domains="{{ lets_encrypt_domains }}"
-        export lets_encrypt_path="{{ lets_encrypt_path }}"
-        export caddy_path="{{ caddy_path }}"
+        set -l lets_encrypt_path "{{ lets_encrypt_path }}"
+        set -l caddy_path "{{ caddy_path }}"
+        set -l ntfy_script "ntfy.fish"
+        set -l sync_output (rsync -ai --include '*/' --exclude '*.issuer.crt' --include '*.crt' --include '*.key' --exclude '*' --prune-empty-dirs "$lets_encrypt_path/.lego/certificates/" "$caddy_path/tls/live/" | awk '$2 != "./" {print $2}')
         
-        read -ra domain_array <<< "$domains"
         
-        counter=0
+        if test -n "$sync_output"
+            echo "Changes detected. Files copied:"
+            echo "$sync_output"
         
-        function check_certs() {
-          for domain in "${domain_array[@]}"; do
-            local source_crt="$lets_encrypt_path/.lego/certificates/$domain.crt"
-            local dest_crt="$caddy_path/tls/live/$domain.crt"
+            if test -x "$ntfy_script"
+                echo "Triggering notification..."
+                ntfy.fish \
+                    --title "Lets Encrypt | Caddy setup certs" \
+                    --tags "lets-encrypt" \
+                    --topic "servers" \
+                    --server_url "{{ ntfy_server }}" \
+                    --message "Files copied: $sync_output" \
+                    --priority "high" \
+                    --apikey "{{ ntfy_api_token }}"
         
-            local source_key="$lets_encrypt_path/.lego/certificates/$domain.key"
-            local dest_key="$caddy_path/tls/live/$domain.key"
-        
-            # Ensure source files exist before trying to compare
-            if [[ ! -f "$source_crt" || ! -f "$source_key" ]]; then
-              echo "ERROR: Source certificate or key for $domain not found. Skipping."
-              continue
-            fi
-        
-            if ! cmp --silent "$source_crt" "$dest_crt" || ! cmp --silent "$source_key" "$dest_key"; then
-              echo "Cert or key for $domain has changed. Incrementing counter."
-              ((counter++))
-            fi
-          done
-        }
-        
-        function copy_certs() {
-          for domain in "${domain_array[@]}"; do
-            echo "------ $domain -------"
-            cp "$lets_encrypt_path/.lego/certificates/$domain.crt" "$caddy_path/tls/live/$domain.crt"
-            cp "$lets_encrypt_path/.lego/certificates/$domain.key" "$caddy_path/tls/live/$domain.key"
-          done
-        }
-        
-        check_certs
-        
-        if [ $counter -gt 0 ]; then
-          ntfy.fish \
-            --title "Lets Encrypt | Caddy setup certs" \
-            --tags "lets-encrypt" \
-            --topic "servers" \
-            --server_url "{{ ntfy_server }}" \
-            --message "Starting to copy Lets Encrypt certificates and restarting Caddy" \
-            --priority "high" \
-            --apikey "{{ ntfy_api_token }}"
-        
-          copy_certs
-        
-          echo "------ Restarting Caddy Server -------"
-          podman exec caddy caddy reload --force --config /etc/caddy/Caddyfile
+                echo "Restarting Caddy Server..."
+                podman exec caddy caddy reload --force --config /etc/caddy/Caddyfile
+            else
+                echo "Error: $ntfy_script not found or not executable."
+                exit 1
+            end
         else
-          echo "No certs changed"
-        fi
+            echo "No new or changed certificates found."
+            exit 0
+        end
       args:
-        executable: /usr/bin/bash
+        executable: /usr/bin/fish
       register: lets_encrypt_cert_setup_output
       changed_when: "'Restarting Caddy Server' in lets_encrypt_cert_setup_output.stdout"
